export const MOCK_TITLES = [
  { id: 1, title: 'Inception', year: 2010 },
  { id: 2, title: 'The Dark Knight', year: 2008 },
  { id: 3, title: 'Interstellar', year: 2014 },
  { id: 4, title: 'Parasite', year: 2019 },
  { id: 5, title: 'The Godfather', year: 1972 },
  { id: 6, title: 'Pulp Fiction', year: 1994 },
  { id: 7, title: 'The Shawshank Redemption', year: 1994 },
  { id: 8, title: 'Fight Club', year: 1999 },
  { id: 9, title: 'Forrest Gump', year: 1994 },
  { id: 10, title: 'The Matrix', year: 1999 },
  { id: 11, title: 'Goodfellas', year: 1990 },
  { id: 12, title: 'The Silence of the Lambs', year: 1991 },
  { id: 13, title: 'Seven', year: 1995 },
  { id: 14, title: 'The Social Network', year: 2010 },
  { id: 15, title: 'Joker', year: 2019 },
  { id: 16, title: 'Avengers: Endgame', year: 2019 },
  { id: 17, title: 'The Avengers', year: 2012 },
  { id: 18, title: 'Guardians of the Galaxy', year: 2014 },
  { id: 19, title: 'Black Panther', year: 2018 },
  { id: 20, title: 'Iron Man', year: 2008 },
  { id: 21, title: 'The Lion King', year: 1994 },
  { id: 22, title: 'Toy Story', year: 1995 },
  { id: 23, title: 'Finding Nemo', year: 2003 },
  { id: 24, title: 'Frozen', year: 2013 },
  { id: 25, title: 'Coco', year: 2017 },
];

export const MOCK_MOVIE_DETAILS: {
  [key: number]: {
    id: number;
    title: string;
    plot_overview: string;
    year: number;
    runtime_minutes: number;
    genres: string[];
    user_rating: number;
    poster: string;
  };
} = {
  1: {
    id: 1,
    title: 'Movie Title 1',
    plot_overview: 'Overview 1',
    year: 2023,
    runtime_minutes: 120,
    genres: ['Action', 'Adventure'],
    user_rating: 7.5,
    poster: 'assets/images/1.webp',
  },
  2: {
    id: 2,
    title: 'Movie Title 2',
    plot_overview: 'Overview 2',
    year: 2022,
    runtime_minutes: 110,
    genres: ['Drama', 'Thriller'],
    user_rating: 8.0,
    poster: 'assets/images/2.jpg',
  },
  3: {
    id: 3,
    title: 'Movie Title 3',
    plot_overview: 'Overview 3',
    year: 2022,
    runtime_minutes: 110,
    genres: ['Drama', 'Thriller'],
    user_rating: 8.0,
    poster: 'assets/images/3.webp',
  },
  4: {
    id: 4,
    title: 'Movie Title 4',
    plot_overview: 'Overview 4',
    year: 2022,
    runtime_minutes: 110,
    genres: ['Drama', 'Thriller'],
    user_rating: 8.0,
    poster: 'assets/images/4.jpeg',
  },
  5: {
    id: 5,
    title: 'Movie Title 5',
    plot_overview: 'Overview 5',
    year: 2022,
    runtime_minutes: 110,
    genres: ['Drama', 'Thriller'],
    user_rating: 8.0,
    poster: 'assets/images/5.jpeg',
  },
  6: {
    id: 6,
    title: 'Movie Title 6',
    plot_overview: 'Overview 6',
    year: 2023,
    runtime_minutes: 95,
    genres: ['Comedy', 'Adventure'],
    user_rating: 7.1,
    poster: 'assets/images/6.jpeg',
  },
  7: {
    id: 7,
    title: 'Movie Title 7',
    plot_overview: 'Overview 7',
    year: 2021,
    runtime_minutes: 100,
    genres: ['Horror', 'Mystery'],
    user_rating: 6.8,
    poster: 'assets/images/7.jpeg',
  },
  8: {
    id: 8,
    title: 'Movie Title 8',
    plot_overview: 'Overview 8',
    year: 2020,
    runtime_minutes: 130,
    genres: ['Action', 'Thriller'],
    user_rating: 8.2,
    poster: 'assets/images/8.jpg',
  },
  9: {
    id: 9,
    title: 'Movie Title 9',
    plot_overview: 'Overview 9',
    year: 2019,
    runtime_minutes: 105,
    genres: ['Romance', 'Drama'],
    user_rating: 7.6,
    poster: 'assets/images/9.jpg',
  },
  10: {
    id: 10,
    title: 'Movie Title 10',
    plot_overview: 'Overview 10',
    year: 2018,
    runtime_minutes: 140,
    genres: ['Sci-Fi', 'Action'],
    user_rating: 8.5,
    poster: 'assets/images/10.webp',
  },
  11: {
    id: 11,
    title: 'Movie Title 11',
    plot_overview: 'Overview 11',
    year: 2023,
    runtime_minutes: 150,
    genres: ['Adventure', 'Fantasy'],
    user_rating: 7.3,
    poster: 'assets/images/11.jpg',
  },
  12: {
    id: 12,
    title: 'Movie Title 12',
    plot_overview: 'Overview 12',
    year: 2021,
    runtime_minutes: 90,
    genres: ['Comedy', 'Drama'],
    user_rating: 6.9,
    poster: 'assets/images/1.webp',
  },
  13: {
    id: 13,
    title: 'Movie Title 13',
    plot_overview: 'Overview 13',
    year: 2022,
    runtime_minutes: 125,
    genres: ['Action', 'Adventure'],
    user_rating: 8.0,
    poster: 'assets/images/2.jpg',
  },
  14: {
    id: 14,
    title: 'Movie Title 14',
    plot_overview: 'Overview 14',
    year: 2019,
    runtime_minutes: 100,
    genres: ['Horror', 'Thriller'],
    user_rating: 7.1,
    poster: 'assets/images/3.webp',
  },
  15: {
    id: 15,
    title: 'Movie Title 15',
    plot_overview: 'Overview 15',
    year: 2018,
    runtime_minutes: 115,
    genres: ['Drama', 'Romance'],
    user_rating: 7.4,
    poster: 'assets/images/4.jpeg',
  },
  16: {
    id: 16,
    title: 'Movie Title 16',
    plot_overview: 'Overview 16',
    year: 2020,
    runtime_minutes: 120,
    genres: ['Fantasy', 'Adventure'],
    user_rating: 8.1,
    poster: 'assets/images/5.jpeg',
  },
  17: {
    id: 17,
    title: 'Movie Title 17',
    plot_overview: 'Overview 17',
    year: 2021,
    runtime_minutes: 110,
    genres: ['Sci-Fi', 'Action'],
    user_rating: 7.9,
    poster: 'assets/images/6.jpeg',
  },
  18: {
    id: 18,
    title: 'Movie Title 18',
    plot_overview: 'Overview 18',
    year: 2022,
    runtime_minutes: 140,
    genres: ['Drama', 'Thriller'],
    user_rating: 8.3,
    poster: 'assets/images/7.jpeg',
  },
  19: {
    id: 19,
    title: 'Movie Title 19',
    plot_overview: 'Overview 19',
    year: 2023,
    runtime_minutes: 105,
    genres: ['Adventure', 'Action'],
    user_rating: 7.7,
    poster: 'assets/images/8.jpg',
  },
  20: {
    id: 20,
    title: 'Movie Title 20',
    plot_overview: 'Overview 20',
    year: 2020,
    runtime_minutes: 125,
    genres: ['Comedy', 'Drama'],
    user_rating: 7.0,
    poster: 'assets/images/9.jpg',
  },
};
